---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sre-frontend-monitor
  namespace: application
  labels:
    team: devops
spec:
  endpoints:
  - port: http
    interval: 2s
  namespaceSelector:
    matchNames:
    - application
  selector:
    matchLabels:
      app: sre-frontend
