---
apiVersion: v1
kind: Service
metadata:
  name: sre-flask
  namespace: application
  labels:
    app: sre-flask
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: sre-flask
